[package]
name = "bitcoin-da"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Chainway <info@chainway.xyz>"]
homepage = "https://www.chainway.xyz"
publish = false
repository = "https://github.com/chainway/bitcoin-da"
rust-version = "1.66"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sov-rollup-interface = { git = "https://github.com/Sovereign-Labs/sovereign-sdk", rev = "617926c" }

tokio = { version = "1", features = [
    "full",
], optional = true, default-features = false }

reqwest = { version = "0.11.13", features = [
    "blocking",
    "json",
], optional = true, default-features = false }
base64 = "0.13.1"
hex = { version = "0.4.3", features = ["serde"] }
tracing = "0.1.37"
rand = "0.8.5"
serde = "1.0.188"
serde_json = { version = "1.0.105", features = ["raw_value"], optional = true }
async-trait = "0.1.73"
borsh = "0.10.3"
anyhow = "1.0.75"
thiserror = "1.0.50"
futures = { version = "0.3", optional = true }
pin-project = { version = "1.1.3", optional = true }

bitcoin = { version = "0.30.1", features = ["serde", "rand"] }
brotli = "3.3.4"
async-recursion = "1.0.5"


[features]
default = []
native = [
    "dep:tokio",
    "dep:reqwest",
    "dep:futures",
    "dep:pin-project",
    "dep:serde_json",
    "sov-rollup-interface/native",
]
verifier = []
